[build]
  publish = "public"
  command = "echo 'No build command needed for PHP application'"

[build.environment]
  PHP_VERSION = "8.0"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  conditions = {Role = ["admin", "editor"]}

# PHP Runtime Configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; img-src 'self' data:; font-src 'self'"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/public/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# PHP file handling
[[redirects]]
  from = "/api/*"
  to = "/public/index.php"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/public/index.php"
  status = 200

[[redirects]]
  from = "/toners/*"
  to = "/public/index.php"
  status = 200

# Fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/public/index.php"
  status = 200
